RM=rm
CP=cp -pu
ECHO=echo
SHELL=/bin/sh

#.SILENT:

build:  move

move:
	$(ECHO) '==> Copying library in $(Project)/rct/lib'
	$(CP) $(BUILD_HOME)/$(Project)/$(Package)/lib/$(XDAQ_OS)/$(XDAQ_PLATFORM)/* $(BUILD_HOME)/$(Project)/caloLayer1/lib/.;
	$(RM) $(BUILD_HOME)/$(Project)/$(Package)/lib/$(XDAQ_OS)/$(XDAQ_PLATFORM)/*;
	$(ECHO)
